// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Epam.AspNet.Education.ApiTests.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class Supplier
    {
        /// <summary>
        /// Initializes a new instance of the Supplier class.
        /// </summary>
        public Supplier() { }

        /// <summary>
        /// Initializes a new instance of the Supplier class.
        /// </summary>
        public Supplier(int? supplierID = default(int?), string companyName = default(string))
        {
            SupplierID = supplierID;
            CompanyName = companyName;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "supplierID")]
        public int? SupplierID { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "companyName")]
        public string CompanyName { get; set; }

    }
}
